# Generated by Django 5.2 on 2025-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargainoffer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bargainoffer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
