# Generated by Django 5.2 on 2025-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bargainoffer_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargainoffer',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
